shellEmulator: true
shamefullyHoist: true
disallowWorkspaceCycles: true
ignoreWorkspaceRootCheck: true

packages:
  - apps/*
  - content/
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
